/* Database schema to keep the structure of entire database. */
-- Create table item
CREATE TABLE ITEM(
  id int GENERATED BY DEFAULT AS IDENTITY,
  publish_date date NOT NULL,
  archived boolean
);

-- Create table music albums
CREATE TABLE MUSIC_ALBUM(
  on_spotify boolean NOT NULL,
  -- inherited from item table
  id int GENERATED BY DEFAULT AS IDENTITY,
  publish_date date NOT NULL,
  archived boolean
) INHERIT(ITEM);

-- Create table genre
CREATE TABLE GENRE(
  id int GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255)
);

-- Alter ITEM table : adding foreign key that references the 'id' in the genre
ALTER TABLE
  ITEM
ADD
  COLUMN genre_id integer REFERENCES GENRE(id);